trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:  
  azureServiceConnection: 'azure-service-connection'
  subscriptionId: 'bde800a0-a73b-44c8-9891-5b403de7d784'
  resourceGroupName: 'rg-aciazpagent-poc'
  location: 'uksouth'
  csmFile: 'ContainerInstanceWithPAT/main.bicep'  
  azpToken: $(azpToken)  # PAT configured as a secret variable

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: $(azureServiceConnection)
    subscriptionId: $(subscriptionId)
    action: 'Create Or Update Resource Group'
    resourceGroupName: $(resourceGroupName)
    location: $(location)
    templateLocation: 'Linked artifact'
    csmFile: $(csmFile)    
    overrideParameters: -imageTag $(Build.BuildId) -azpToken $(azpToken)
    deploymentMode: 'Incremental'